# Generated by Django 4.1.6 on 2023-04-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects", name="body", field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="projects",
            name="employee_img",
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="img",
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
