# Generated by Django 4.1.6 on 2023-04-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_projects_body_alter_projects_employee_img_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Projects",),
    ]
