# Generated by Django 4.1.6 on 2023-04-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="projects", name="employee_img",),
        migrations.RemoveField(model_name="projects", name="img",),
    ]
