# Generated by Django 4.1.6 on 2023-04-10 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_projects_employee_img_remove_projects_img"),
    ]

    operations = [
        migrations.DeleteModel(name="Projects",),
    ]
