# Generated by Django 4.1.6 on 2023-04-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Projects",),
    ]
