# Generated by Django 4.1.6 on 2023-04-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_projects_employee_2_projects_employee_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projects", old_name="employee_2", new_name="employee2",
        ),
        migrations.AddField(
            model_name="projects",
            name="employee2_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
