# Generated by Django 4.1.6 on 2023-04-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_rename_employee_2_projects_employee2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="employee2_img",
            field=models.FileField(blank=True, null=True, upload_to="images"),
        ),
    ]
