# Generated by Django 4.1.6 on 2023-04-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_projects_employee2_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="employee2_img",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="images"
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="employee2_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="employee_img",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="images"
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="employee_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="project_url",
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
